-- ============================================
-- 数据同步工具 - 初始化建表脚本 (Oracle语法)
-- 若本地库为MySQL/DM，需做少量语法调整
-- ============================================

-- 1. 数据库连接配置表
CREATE TABLE SYNC_DB_CONN (
    ID              VARCHAR2(36)    PRIMARY KEY,
    NAME            VARCHAR2(100)   NOT NULL,
    DB_TYPE         VARCHAR2(20)    NOT NULL,
    HOST            VARCHAR2(200),
    PORT            NUMBER(10),
    DATABASE_NAME   VARCHAR2(200),
    JDBC_URL        VARCHAR2(500)   NOT NULL,
    USERNAME        VARCHAR2(100)   NOT NULL,
    PASSWORD        VARCHAR2(200)   NOT NULL,
    DRIVER_CLASS    VARCHAR2(200),
    SCHEMA          VARCHAR2(200),
    REMARK          VARCHAR2(500),
    STATUS          NUMBER(1)       DEFAULT 1,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE  SYNC_DB_CONN              IS '数据库连接配置表';
COMMENT ON COLUMN SYNC_DB_CONN.ID           IS '主键(UUID)';
COMMENT ON COLUMN SYNC_DB_CONN.NAME         IS '连接名称';
COMMENT ON COLUMN SYNC_DB_CONN.DB_TYPE      IS '数据库类型: oracle/mysql/dm/postgresql/sqlserver';
COMMENT ON COLUMN SYNC_DB_CONN.HOST         IS '主机地址';
COMMENT ON COLUMN SYNC_DB_CONN.PORT         IS '端口号';
COMMENT ON COLUMN SYNC_DB_CONN.DATABASE_NAME IS '数据库名/SID/实例名';
COMMENT ON COLUMN SYNC_DB_CONN.JDBC_URL     IS 'JDBC连接地址';
COMMENT ON COLUMN SYNC_DB_CONN.USERNAME     IS '用户名';
COMMENT ON COLUMN SYNC_DB_CONN.PASSWORD     IS '密码';
COMMENT ON COLUMN SYNC_DB_CONN.DRIVER_CLASS IS '驱动类(可根据DB_TYPE自动填充)';
COMMENT ON COLUMN SYNC_DB_CONN.SCHEMA       IS 'Schema/模式名(DM等数据库schema不一定等于username)';
COMMENT ON COLUMN SYNC_DB_CONN.REMARK       IS '备注';
COMMENT ON COLUMN SYNC_DB_CONN.STATUS       IS '1=有效, 0=无效';

-- 2. 调度配置表
CREATE TABLE SCHEDULE (
    ID              VARCHAR2(36)    PRIMARY KEY,
    NAME            VARCHAR2(200)   NOT NULL,
    CRON            VARCHAR2(100),
    ONCE            NUMBER(1)       DEFAULT 0,
    DESC_           VARCHAR2(500),
    ENABLED         NUMBER(1)       DEFAULT 1,
    STATUS          NUMBER(1)       DEFAULT 1,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE  SCHEDULE                IS '调度配置表';
COMMENT ON COLUMN SCHEDULE.ID             IS '主键(UUID)';
COMMENT ON COLUMN SCHEDULE.NAME           IS '调度名称';
COMMENT ON COLUMN SCHEDULE.CRON           IS 'Cron表达式(秒 分 时 日 月 周 [年])，once=1时可为空';
COMMENT ON COLUMN SCHEDULE.ONCE           IS '是否一次性调度: 0=周期调度(按Cron执行), 1=一次性调度(仅手动触发)';
COMMENT ON COLUMN SCHEDULE.DESC_          IS '描述说明';
COMMENT ON COLUMN SCHEDULE.ENABLED        IS '是否启用: 1=启用, 0=禁用';
COMMENT ON COLUMN SCHEDULE.STATUS         IS '1=有效, 0=无效(逻辑删除)';

-- 3. 同步任务配置表
CREATE TABLE SYNC_TASK (
    ID                VARCHAR2(36)    PRIMARY KEY,
    NAME              VARCHAR2(200)   NOT NULL,
    SOURCE_CONN_ID    VARCHAR2(36)    NOT NULL,
    TARGET_CONN_ID    VARCHAR2(36)    NOT NULL,
    SOURCE_TABLE      VARCHAR2(200)   NOT NULL,
    TARGET_TABLE      VARCHAR2(200)   NOT NULL,
    SOURCE_SQL        CLOB,
    PRIMARY_KEYS      VARCHAR2(500),
    FIELD_MAPPING     CLOB,
    CUSTOM_PK         VARCHAR2(500),
    MARKER_FIELD      VARCHAR2(100),
    LAST_MARKER_VALUE VARCHAR2(255),
    CHECKPOINT_DATA   CLOB,
    SOURCE_WHERE      VARCHAR2(1000),
    STRATEGY          VARCHAR2(20)    DEFAULT 'incremental',
    FETCH_MODE        VARCHAR2(20)    DEFAULT 'parallel',
    SYNC_MODE         NUMBER(1)       DEFAULT 1,
    BATCH_SIZE        NUMBER(10)      DEFAULT 1000,
    TASK_GROUP        VARCHAR2(100),
    SCHEDULE_ID       VARCHAR2(36),
    RUN_STATUS        VARCHAR2(20)    DEFAULT 'stopped',
    LAST_RUN_TIME     TIMESTAMP,
    NEXT_RUN_TIME     TIMESTAMP,
    TOTAL_ROWS_SYNCED NUMBER(20)      DEFAULT 0,
    NO_UPDATE         NUMBER(1)       DEFAULT 0,
    STATUS            NUMBER(1)       DEFAULT 1,
    REMARK            VARCHAR2(500),
    CREATE_TIME       TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME       TIMESTAMP       DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE  SYNC_TASK                  IS '同步任务配置表';
COMMENT ON COLUMN SYNC_TASK.ID               IS '主键(UUID)';
COMMENT ON COLUMN SYNC_TASK.NAME             IS '任务名称';
COMMENT ON COLUMN SYNC_TASK.SOURCE_CONN_ID   IS '源库连接ID';
COMMENT ON COLUMN SYNC_TASK.TARGET_CONN_ID   IS '目标库连接ID';
COMMENT ON COLUMN SYNC_TASK.SOURCE_TABLE     IS '源表名';
COMMENT ON COLUMN SYNC_TASK.TARGET_TABLE     IS '目标表名';
COMMENT ON COLUMN SYNC_TASK.SOURCE_SQL       IS '自定义源SQL(非表名时使用), 优先级高于SOURCE_TABLE';
COMMENT ON COLUMN SYNC_TASK.PRIMARY_KEYS     IS '主键字段列表(逗号分隔), 从field_mappings中isPk=true提取';
COMMENT ON COLUMN SYNC_TASK.FIELD_MAPPING    IS '字段映射JSON, 如[{"srcField":"LSH","tgtField":"LSH"}] 或 {"SRC_COL":"TGT_COL"}, 空则同名映射';
COMMENT ON COLUMN SYNC_TASK.CUSTOM_PK        IS '用户自定义主键(逗号分隔), 空则读取原表主键';
COMMENT ON COLUMN SYNC_TASK.MARKER_FIELD     IS '增量标记字段名(如UPDATE_TIME/GXSJ), 对应API的increment_field';
COMMENT ON COLUMN SYNC_TASK.LAST_MARKER_VALUE IS '上次同步的标记值';
COMMENT ON COLUMN SYNC_TASK.CHECKPOINT_DATA  IS '断点续传数据(JSON: completed+incomplete), stop后清除';
COMMENT ON COLUMN SYNC_TASK.SOURCE_WHERE     IS '额外查询条件(WHERE条件)';
COMMENT ON COLUMN SYNC_TASK.STRATEGY         IS '同步策略: incremental/full/cdc';
COMMENT ON COLUMN SYNC_TASK.FETCH_MODE       IS '读取模式: parallel(并行分页)/streaming(流式)';
COMMENT ON COLUMN SYNC_TASK.SYNC_MODE        IS '同步模式: 1=MERGE, 2=INSERT_ONLY, 3=CLEAN_INSERT';
COMMENT ON COLUMN SYNC_TASK.BATCH_SIZE       IS '批量大小, 默认1000';
COMMENT ON COLUMN SYNC_TASK.TASK_GROUP       IS '任务分组';
COMMENT ON COLUMN SYNC_TASK.SCHEDULE_ID      IS '关联调度ID';
COMMENT ON COLUMN SYNC_TASK.RUN_STATUS       IS '运行状态: running/paused/stopped/error';
COMMENT ON COLUMN SYNC_TASK.LAST_RUN_TIME    IS '最后执行时间';
COMMENT ON COLUMN SYNC_TASK.NEXT_RUN_TIME    IS '下次执行时间';
COMMENT ON COLUMN SYNC_TASK.TOTAL_ROWS_SYNCED IS '已同步总行数';
COMMENT ON COLUMN SYNC_TASK.NO_UPDATE        IS '仅插入不更新: 1时MERGE模式只INSERT不UPDATE已存在记录';
COMMENT ON COLUMN SYNC_TASK.STATUS           IS '1=有效, 0=无效(逻辑删除)';

-- 4. 同步任务执行日志表
CREATE TABLE SYNC_TASK_LOG (
    ID              VARCHAR2(36)    PRIMARY KEY,
    TASK_ID         VARCHAR2(36)    NOT NULL,
    TASK_NAME       VARCHAR2(200),
    SYNC_MODE       NUMBER(1),
    STATUS          NUMBER(1)       DEFAULT 1,
    TOTAL_COUNT     NUMBER(10)      DEFAULT 0,
    SUCCESS_COUNT   NUMBER(10)      DEFAULT 0,
    FAIL_COUNT      NUMBER(10)      DEFAULT 0,
    INSERT_COUNT    NUMBER(10)      DEFAULT 0,
    UPDATE_COUNT    NUMBER(10)      DEFAULT 0,
    SKIP_COUNT      NUMBER(10)      DEFAULT 0,
    ERROR_MSG       CLOB,
    START_TIME      TIMESTAMP,
    END_TIME        TIMESTAMP
);
COMMENT ON TABLE  SYNC_TASK_LOG              IS '同步任务执行日志表';
COMMENT ON COLUMN SYNC_TASK_LOG.STATUS       IS '1=运行中, 2=成功, 3=失败';

-- ======================== 系统用户表 ========================
CREATE TABLE SYNC_USERS (
    ID          VARCHAR(64)   PRIMARY KEY,
    USERNAME    VARCHAR(64)   NOT NULL UNIQUE,
    PASSWORD    VARCHAR(256)  NOT NULL,
    REAL_NAME   VARCHAR(128),
    ROLE        VARCHAR(32)   DEFAULT 'user',
    STATUS      INTEGER       DEFAULT 1,
    CREATE_TIME TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);
-- 默认管理员账号: admin / admin123
INSERT INTO SYNC_USERS(ID, USERNAME, PASSWORD, REAL_NAME, ROLE)
VALUES('u001', 'admin', '$2a$10$IJdrJFRkmrPVFOk9.kpby.8aaBOZcO6vbSRudg/gDleMMSaNBE0hW', '管理员', 'admin');
COMMENT ON TABLE  SYNC_USERS              IS '系统用户表';
COMMENT ON COLUMN SYNC_USERS.STATUS       IS '1=正常, 0=禁用';
